plugins = []
functionsDirectory = "/Users/josephanady/donation_platform/functions"
functionsDirectoryOrigin = "config"
headers = []

[build]
edge_functions = "/Users/josephanady/donation_platform/netlify/edge-functions"
publish = "/Users/josephanady/donation_platform/static"
publishOrigin = "config"
commandOrigin = "config"
command = "node netlify-build.mjs"
functions = "/Users/josephanady/donation_platform/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = ""
publish = "static"

[[edge_functions]]
function = "sanitize_html"
path = "/"

[[edge_functions]]
function = "sanitize_html"
path = "/index.html"

[[edge_functions]]
function = "sanitize_html"
path = "/backend"

[functions]

[functions."*"]

[[redirects]]
from = "/backend"
to = "/backend.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]