[build]
  command = "npm install && npm run build"
  publish = "static"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  directory = "functions"

# Optional: local dev via `netlify dev` (serves from static)
[dev]
  command = ""
  publish = "static"

[[edge_functions]]
  function = "sanitize_html"
  path = "/"

[[edge_functions]]
  function = "sanitize_html"
  path = "/index.html"

[[edge_functions]]
  function = "sanitize_html"
  path = "/backend"
